/** Avatar bg classes — keep in sync with Payload select + MessageGroup text map. */
export const PARTICIPANT_COLOR_OPTIONS = [
  // Warm
  { label: 'Rose',     value: 'bg-rose-400' },
  { label: 'Rose deep', value: 'bg-rose-500' },
  { label: 'Red',      value: 'bg-red-400' },
  { label: 'Red deep', value: 'bg-red-500' },
  { label: 'Orange',   value: 'bg-orange-400' },
  { label: 'Orange deep', value: 'bg-orange-500' },
  { label: 'Amber',    value: 'bg-amber-400' },
  { label: 'Amber deep', value: 'bg-amber-500' },
  { label: 'Yellow',   value: 'bg-yellow-400' },
  { label: 'Yellow deep', value: 'bg-yellow-500' },
  // Green
  { label: 'Lime',     value: 'bg-lime-400' },
  { label: 'Lime deep', value: 'bg-lime-500' },
  { label: 'Green',    value: 'bg-green-400' },
  { label: 'Green deep', value: 'bg-green-500' },
  { label: 'Emerald',  value: 'bg-emerald-400' },
  { label: 'Emerald deep', value: 'bg-emerald-500' },
  { label: 'Teal',     value: 'bg-teal-400' },
  { label: 'Teal deep', value: 'bg-teal-500' },
  // Cool
  { label: 'Cyan',     value: 'bg-cyan-400' },
  { label: 'Cyan deep', value: 'bg-cyan-500' },
  { label: 'Sky',      value: 'bg-sky-400' },
  { label: 'Sky deep', value: 'bg-sky-500' },
  { label: 'Blue',     value: 'bg-blue-400' },
  { label: 'Blue deep', value: 'bg-blue-500' },
  { label: 'Indigo',   value: 'bg-indigo-400' },
  { label: 'Indigo deep', value: 'bg-indigo-500' },
  { label: 'Violet',   value: 'bg-violet-400' },
  { label: 'Violet deep', value: 'bg-violet-500' },
  { label: 'Purple',   value: 'bg-purple-400' },
  { label: 'Purple deep', value: 'bg-purple-500' },
  { label: 'Fuchsia',  value: 'bg-fuchsia-400' },
  { label: 'Fuchsia deep', value: 'bg-fuchsia-500' },
  { label: 'Pink',     value: 'bg-pink-400' },
  { label: 'Pink deep', value: 'bg-pink-500' },
  // Neutrals
  { label: 'Stone',    value: 'bg-stone-400' },
  { label: 'Stone deep', value: 'bg-stone-500' },
  { label: 'Slate',    value: 'bg-slate-400' },
  { label: 'Slate deep', value: 'bg-slate-500' },
  { label: 'Zinc',     value: 'bg-zinc-400' },
  { label: 'Zinc deep', value: 'bg-zinc-500' },
  { label: 'Gray',     value: 'bg-gray-400' },
  { label: 'Gray deep', value: 'bg-gray-500' },
] as const

export type ParticipantColor = (typeof PARTICIPANT_COLOR_OPTIONS)[number]['value']

export const DEFAULT_PARTICIPANT_COLOR = 'bg-violet-400' as const satisfies ParticipantColor

export const ALLOWED_PARTICIPANT_COLORS = new Set<string>(
  PARTICIPANT_COLOR_OPTIONS.map(c => c.value),
)

/** Sender name text color paired with each avatar bg. */
export const PARTICIPANT_TEXT_COLORS: Record<string, string> = {
  'bg-rose-400':    'text-rose-600 dark:text-rose-400',
  'bg-rose-500':    'text-rose-700 dark:text-rose-400',
  'bg-red-400':     'text-red-600 dark:text-red-400',
  'bg-red-500':     'text-red-700 dark:text-red-400',
  'bg-orange-400':  'text-orange-600 dark:text-orange-400',
  'bg-orange-500':  'text-orange-700 dark:text-orange-400',
  'bg-amber-400':   'text-amber-700 dark:text-amber-400',
  'bg-amber-500':   'text-amber-800 dark:text-amber-400',
  'bg-yellow-400':  'text-yellow-700 dark:text-yellow-400',
  'bg-yellow-500':  'text-yellow-800 dark:text-yellow-400',
  'bg-lime-400':    'text-lime-700 dark:text-lime-400',
  'bg-lime-500':    'text-lime-800 dark:text-lime-400',
  'bg-green-400':   'text-green-700 dark:text-green-400',
  'bg-green-500':   'text-green-800 dark:text-green-400',
  'bg-emerald-400': 'text-emerald-700 dark:text-emerald-400',
  'bg-emerald-500': 'text-emerald-800 dark:text-emerald-400',
  'bg-teal-400':    'text-teal-700 dark:text-teal-400',
  'bg-teal-500':    'text-teal-800 dark:text-teal-400',
  'bg-cyan-400':    'text-cyan-700 dark:text-cyan-400',
  'bg-cyan-500':    'text-cyan-800 dark:text-cyan-400',
  'bg-sky-400':     'text-sky-600 dark:text-sky-400',
  'bg-sky-500':     'text-sky-700 dark:text-sky-400',
  'bg-blue-400':    'text-blue-600 dark:text-blue-400',
  'bg-blue-500':    'text-blue-700 dark:text-blue-400',
  'bg-indigo-400':  'text-indigo-600 dark:text-indigo-400',
  'bg-indigo-500':  'text-indigo-700 dark:text-indigo-400',
  'bg-violet-400':  'text-violet-600 dark:text-violet-400',
  'bg-violet-500':  'text-violet-700 dark:text-violet-400',
  'bg-purple-400':  'text-purple-600 dark:text-purple-400',
  'bg-purple-500':  'text-purple-700 dark:text-purple-400',
  'bg-fuchsia-400': 'text-fuchsia-600 dark:text-fuchsia-400',
  'bg-fuchsia-500': 'text-fuchsia-700 dark:text-fuchsia-400',
  'bg-pink-400':    'text-pink-600 dark:text-pink-400',
  'bg-pink-500':    'text-pink-700 dark:text-pink-400',
  'bg-stone-400':   'text-stone-700 dark:text-stone-400',
  'bg-stone-500':   'text-stone-800 dark:text-stone-400',
  'bg-slate-400':   'text-slate-700 dark:text-slate-400',
  'bg-slate-500':   'text-slate-800 dark:text-slate-400',
  'bg-zinc-400':    'text-zinc-700 dark:text-zinc-400',
  'bg-zinc-500':    'text-zinc-800 dark:text-zinc-400',
  'bg-gray-400':    'text-gray-700 dark:text-gray-400',
  'bg-gray-500':    'text-gray-800 dark:text-gray-400',
}
